import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js Signin",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
