import type { Metadata } from "next";
import "./globals.css";
import { NextAuthWrapper } from "@/lib/next.auth.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NextAuthWrapper>{props.children}</NextAuthWrapper>
      </body>
    </html>
  );
}
