import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/components/theme-registry/theme.registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: any) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>{props.children} </ThemeRegistry>
      </body>
    </html>
  );
}
