import AppBarHomePage from "@/components/Appbar.homepage";
import DrawerHomePage from "@/components/Drawer.homepage";
import { Box } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nextjs Homepage",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <Box
      sx={{
        display: "flex",
        borderRadius: 2,
      }}
    >
      <DrawerHomePage />
      <Box sx={{ width: "80vw" }}>
        <Box height={64}>
          <AppBarHomePage />
        </Box>

        <Box sx={{ display: "flex" }}>
          <Box sx={{ border: "1px solid red", width: "70%" }}>
            {props.children}
          </Box>
          <Box sx={{ border: "1px solid blue", width: "30%" }}></Box>
        </Box>
      </Box>
    </Box>
  );
}
